### ISSUE TITLE
plot of sf objects with add = TRUE failing

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/vector-analysis-syracuse-lesson#2]
Works in RStudio, but does not show up in RMarkdown rendered images.

**Comment by khondula** [comment]
might need to add st_geometry() to first plotting instance?

**Comment by khondula** [comment]
https://github.com/r-spatial/sf/issues/685 may be related

**Comment by itcarroll** [comment]
Did try installing github from the master branch of tidyverse/ggplo2 (to get version > 2.2.1), it works very nicely with, e.g.

```
library(sf)
ct <- read_sf('data/ct_00')
bg <- read_sf('data/bg_00')

library(ggplot2)
ggplot() +
  geom_sf(data = ct, aes(fill = Shape_Area)) +
  geom_sf(data = bg, color = 'red', fill = NA)
```

**Comment by itcarroll** [comment]
fixed by rolling back sf to previous release
